### ISSUE TITLE
Support for structure fields in site.yml

### ISSUE THREAD

**Issue by JonasDoebertin** [bnomei/kirby3-autoid#15]
As of right now, support for structure fields in `site.yml` is not supported, as it seems.

A common use case for me is to have site-wide definitions in structure fields in `site.yml` and reference them on other pages.

Do you want additional input for this?

**Comment by bnomei** [comment]
that is since the `site()` is not a real page but your point is legit. i will think about what to do.

**Comment by bnomei** [comment]
i do not think i can support this in the near future. since the site is not a real page object i would require a lot of work to support it as well adding a lot of code.
i you case you could use a regular page and link it with a page field to the site. this way you could do something like: `site()->myglobalstructs()->toPage()` and retrieve the values from there.

**Comment by raphaelokon** [comment]
@JonasDoebertin Did you ever find a workaround? I wish we could have autoids on site fields as well. @bnomei Are there any workarounds you would recommend to circumvent the limitation? Thanks for the great plugin.

**Comment by bnomei** [comment]
@raphaelokon i will do a refactorisation to add unittests soon(ish) and i will and it then. some time during august/september 2019.
