### ISSUE TITLE
Does translate: false work in structures?

### ISSUE THREAD

**Issue by dinko** [bnomei/kirby3-autoid#18]
I've tried to use `translate: false` in structures, yet, new autoids are created. When I think about, it would totally make sense it does not work, wouldn't know how references could be made between the languages.

Anyway…thx in advance for clarifying!

**Comment by bnomei** [comment]
i think you can only set the comlete structure to non translatable not fields within the structure entry.

**Comment by dinko** [comment]
Cool, thx for clarifying. Maybe you want change your example (under section "Setup"), there a `translate` is within the structure.

**Comment by iskrisis** [comment]
This is a bit more nuanced i think. The autoids don't seem to be generated. The issue with translating structures is that they can become completely "disconnected" in translations. So the `translate: false` works but when i change the order in the translation or make completely different structure items - they wont have the corresponding default language variant thus wont have autoid. This might lead to really nasty bugs. If i understand correctly language variant looks for default language content as fallback and uses order number to get it. So if i translate structure and just change order - my translation will be finding autoids of different items.

Indeed only solution is either disable translate entirely or use pages instead of structure.
