### ISSUE TITLE
The `vendor` should not be under Git version control

### ISSUE THREAD

**Issue by peter279k** [bnomei/kirby3-autoid#26]
As title, it looks like the `vendor` directory is under the Git version control.

However, the `vendor` directory is about the dependencies directory and this will be generated by running `composer install` command.

This directory should be removed and add this in the `.gitignore` file.

**Comment by bnomei** [comment]
if this repo would be a regular php repo indeed you would be right. but since its a kirby 3 plugin which adhers to all three supported installation types (manual master zip, gitsubmodule, composer) having the vendor folder is correct. also the used `.gitignore` file trims away almost all vendor files but php code so the footprint is minimal.

see official kirby 3 pluginkit for more information.
https://github.com/getkirby/pluginkit
