### ISSUE TITLE
PDOException on save

### ISSUE THREAD

**Issue by wout** [bnomei/kirby3-autoid#39]
I thought I would never see this in Kirby. :)

![image](https://user-images.githubusercontent.com/107324/71769079-54fdec00-2f14-11ea-983e-5ce25a1e4cfd.png)

I had to install the `php-sqlite3` extension to make it work. But this got me wondering, does this plugin keep a list of ids? What if the cache folder is busted?

For example, I use [Capistrano](https://capistranorb.com/) to deploy this particular Kirby project. Capistrano keeps a number of previous releases and I don't keep `cache`, `media` nor `content` in the repo. So on every deploy, all cache files are left with the previous release, starting out with a new cache after every deploy.

What does this mean for autoid? Will there be a loss of data?

**Comment by bnomei** [comment]
hi @wout . sorry to respond so late.

i agree i should state clearer that the current version of autoid uses a sqlite DB to be as fast as possible. it greatly speeds up reindexing as well as multiple lookups during a single page call.

there will be no loss of data but for after deploy at the first usage of autoid the sqlite db will be created anew and a reindex will be performed. 
you might run into issues if the reindex is not able to complete within the usual 30sec php script timeout. this could be avoided if you use janitor as cli to trigger the reindex right after the deploy. i will add that later today since i need it for a project of mine as well.

**Comment by janherman** [comment]
Is there a minimum required version of SQLite library for AutoID to work?
